version: "3.8"

services:
  postgres-loginless:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: public
    ports:
      - "5432:5432"

  redis-loginless:
    image: "redis:alpine"
    ports:
      - "6379:6379"
